### ISSUE TITLE
Some thoughts on using RHOASTER

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/rhoaster#2]
### Remove builds and image streams during cleanup

So currently, during the cleanup after the tests, we run the `undeploy` method from nodeshift which cleans up the application specific stuff that gets created(routes, services, etc....).  

We should probably also cleanup any builds, buildConfigs and Imagestreams that get created.

Currently there is no method exposed in nodeshift that does this.  However; there is a bit of code that does this during the build phase if you pass in the `build.recreate` option.  we could probably break this code out to be its own method.  i don't really like the name `unbuild` but it is what it do.

### deploymentName as the Project name

When i first used rhoaster, i thought deploymentName was going to be substituted in for the project name, but then i realized, it needs to be whats in the projects package.json so it knows what to ping.

I wonder if we should overwrite the project name from the package.json with the deployment name instead.  this way if there is a "real" version of the app running, this wouldn't interfere with it.

Although, they probably shouldn't be doing that anyway :)

@helio-frota  @danbev @lance thoughts?

**Comment by lance** [comment]
I'm not sure overwriting the value in `package.json` is great. Modifying user code - even if it is just metadata seems wrong to me. From your comment it's not clear to me what the actual conflict is. Does the problem occur when you have a `deploymentName` in your `.yml` that doesn't match `project.json`?

**Comment by lholmquist** [comment]
when i had the deploymentName different than the project name(in package.json),   rhoaster would time out, which made sense since it was looking for `nodejs-rest-http-integration` for example, but the actual name of the exposed url was `nodejs-rest-http`.    once i realized how to use it, it was fine :)

i guess my concern was avoiding conflicts with something that is already deployed.   i was thinking that all the test stuff should have its own unique name.

what are your thoughts on the remove build stuff?

**Comment by lance** [comment]
Hmm - I think keeping the buildconfig and imagestreams in openshift is good. Otherwise, wouldn't you need to recreate them with every new deployment?

**Comment by lholmquist** [comment]
you would, but i guess my thought was, once you are done with all the integration tests, shouldn't we cleanup everything that was created during the process.

**Comment by lance** [comment]
Ahh yes. I was mistakenly thinking that you meant for all uses of nodeshift

**Comment by lholmquist** [comment]
the removeall thought is part of #4

**Comment by lholmquist** [comment]
closing now
