### ISSUE TITLE
Add an option to not undeploy the app

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/rhoaster#8]
Sorry I really don't remember the use case for this, but I remember that was useful sometimes to not undeploy the app.

**Comment by helio-frota** [comment]
```
#bucharest-gold.log:Feb 19 11:00:20 <helio-frota>	2. I can use minishift + rhoaster locally but since it does undeploy , it makes more difficult to understand what's happening with the integration test
#bucharest-gold.log:Feb 19 11:10:56 <lholmquist>	helio-frota: just uncomment the part that undeploys :)
```

**Comment by lholmquist** [comment]
I don't think rhoaster will undeploy unless you call `undeploy` directly,  so i don't think there needs to be an option

i think i remember this conversation.  we were talking about this i think,  https://github.com/lholmquist/nodejs-rest-http/blob/582adfc8d660838b4b7687fc642bde776705609a/test/integration/greeting-integration-test.js#L13

**Comment by helio-frota** [comment]
yup was something like this.
maybe don't need to be 1 option for sure.
I'm going to close this issue, thanks!
